version: '3.8'

services:
  analyze-app:
    build: .
    environment:
      - DIR_IN=/data/bithumb/minute/bithumb
      - DIR_OUT=/data/bithumb/merge
      - DIR_RESULT=/data/bithumb/result
      - FILE_OUT=merged_XRP_data.csv
    volumes:
      - ${DATA_DIR}:/usr/src/app/data
    command: python ./main.py