server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jyshine/config-repo.git
#        native:
#          search-locations: file://${user.home}/dev/git/native-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
